### ISSUE TITLE
Lost connection with Google Analytics

### ISSUE THREAD

**Issue by hesteric** [unclecheese/silverstripe-dashboard#60]
Hi,

Since some weeks there is no connection with Google Analytics anymore:

The account information you have entered for Google Analytics appears to be invalid. Please check the email and password combination and try again.

This happens with all our SilverStripe websites where it was always worked well, but also on new installations.
Checked everything in the Google account, like the security level for apps...

Any idea?

**Comment by hesteric** [comment]
Since today it works again on all the websites without any changes. I don't know what was wrong, I guess something at the side of Google...

**Comment by unclecheese** [comment]
It's still very much an issue. Google changes their API quite often, and the way the analytics is being injected into the UI is a bit dodgy (i.e. we've circumvented the whole `google.load()` workflow) so I'm not surprised it keeps breaking. We need a more robust solution, ultimately.

**Comment by unclecheese** [comment]
Google upgraded their API with new Oauth requirements. The `1.1.0` release of dashboard uses this new API. That should bring a permanent resolution to all of the connection issues.

Be advised, however, that the new API is much different. Be sure to read the updated README. `set_account()` is no more.
