### ISSUE TITLE
can't have page in site tree wit h dashboard url segment.

### ISSUE THREAD

**Issue by mediabeastnz** [unclecheese/silverstripe-dashboard#61]
You can't have page in site tree wit h dashboard url segment as it just redirects to the admin dashboard instead of the page.

Be great if this was editable, i need a dashboard for both frontend and admin.

**Comment by unclecheese** [comment]
The url segment for the dashboard is `admin/dashboard`. Do you have a page named "admin/dashboard"??

**Comment by mediabeastnz** [comment]
No just an account page from SS shop that was renamed to Dashboard. So the url-segment ended up being "dashboard".

I then attach a couple routes for extra features on the dashboard for example:

```
Director:
  rules:
   'dashboard/memberships//$Action/$ID/$Name':    'MembershipProduct_Controller'
```

**Comment by unclecheese** [comment]
I just tested your code and I wasn't able to replicate the problem. The Dashboard is off the `admin/` url base, so there's no reason why a controller on `dashboard/` should be in conflict.

In any case, Dashboard is just a LeftAndMain controller, so the `url_segment` is just a config setting.

```
Dashboard:
  url_segment: whatever
```

**Comment by mediabeastnz** [comment]
Hmm weird, must be something else in my configuration...

Thanks for your help anyway! Appreciated.
