### ISSUE TITLE
Quick links are not sorting 

### ISSUE THREAD

**Issue by mi32dogs** [unclecheese/silverstripe-dashboard#62]
Hi,

First of all thanks for all the great modules, they are very helpful.

I have a little problem with the quick links, they are not sorting.
I get the flowing error in firebug http://192.168.1.100/dash/admin/dashboard/panel/2/ConfigureForm/field/Links/sort?item[]=2&item[]=1 404 Not found
Action 'sort' isn't available on class DashboardHasManyRelationEditor.

Thank you

**Comment by unclecheese** [comment]
Can you try adding it to the `allowed_actions`, and see if that works? If it does, please submit a PR.

**Comment by mi32dogs** [comment]
I tried that but that did not make a difference.
What is a PR? 

Thanks

**Comment by unclecheese** [comment]
Did your remember to `?flush`? Changes to private statics are cached.

`PR = 'pull request';`

**Comment by mi32dogs** [comment]
I'm so sorry, i thought a did many ?flush=all 's but i must have done something wrong or having a big brain fart here. 
it is working perfectly now. Thank you
